### ISSUE TITLE
not a meme: Ohio

### ISSUE THREAD

**Issue by frigidus5** [3kh0/state-test#14]
this repository will get shut down due to legal reasons lol

**Comment by 3kh0** [comment]
perhaps

**Comment by frigidus5** [comment]
![2023-05-28-161330_3440x1440_scrot](https://github.com/3kh0/state-test/assets/129239408/8c6f7973-bfb9-4ed3-a4a9-8a79d5c9f045)
this is a joke. it must be. i cannot accept this.

**Comment by frigidus5** [comment]
https://login5.cambiumtds.com/student_core/V90/Pages/LoginShell.aspx?c=California
close to this?
