### ISSUE TITLE
Ok so there is a glaring issue with this

### ISSUE THREAD

**Issue by Scaratek** [3kh0/state-test#3]
This is just enabling skids to cheat on their state tests
not very smart......

**Comment by Scaratek** [comment]
wdym "so"?
i have a feeling your one of the people im talking about
**cheating on your state test is BAD**
dont do it!
but skids are stupid and dont know that

**Comment by 3kh0** [comment]
Yes, that is what a skid would do. The point is that schools need to up their game.

**Comment by Scaratek** [comment]
My point is if your gonna make a repo about how to take state tests without using kiosk apps at least make the skids dump the kiosk apps them self.

**Comment by 3kh0** [comment]
I see, I understand your worry, but skids somehow can not follow the instructions for ltmeat and that is very simple
